version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phototours_db
    ports:
      - "5432:5432"
    volumes:
      - rag_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  rag-service:
    build: .
    container_name: rag-service
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8010:8010"
    env_file:
      - .env

volumes:
  rag_pgdata: